import { Question } from "./types";

export const QUESTIONS: Question[] = [
  {
    id: "rating",
    prompt: "What's your current rating, and how do you know it?",
    helperText: 'e.g. "3.5 DUPR", "self-rated around 3.7"',
    type: "context",
    required: true,
  },
  {
    id: "plateau_duration",
    prompt: "How long have you felt stuck at your current level?",
    type: "context",
    required: true,
    options: [
      { id: "a", label: "Under 6 months" },
      { id: "b", label: "6–12 months" },
      { id: "c", label: "1–2 years" },
      { id: "d", label: "2+ years" },
      { id: "e", label: "I don't feel stuck, I just want to improve" },
    ],
  },
  {
    id: "play_frequency",
    prompt: "In a typical week, how many times do you play and for about how long?",
    helperText: 'e.g. "3x a week, 2 hours each"',
    type: "context",
    required: true,
  },
  {
    id: "open_play_ratio",
    prompt: "Of your time on court, how much is open play / games vs. structured drilling?",
    type: "training",
    required: true,
    options: [
      { id: "a", label: "Almost all open play / games", rootCauseFlag: "open_play_only" },
      { id: "b", label: "Mostly games, occasional drilling", rootCauseFlag: "open_play_only" },
      { id: "c", label: "A real mix of both", rootCauseFlag: "unclear" },
      { id: "d", label: "Mostly drilling and focused practice", rootCauseFlag: "well_coached" },
    ],
  },
  {
    id: "drilling_quality",
    prompt: "When you do drill, what does it usually look like?",
    type: "training",
    required: true,
    options: [
      { id: "a", label: "I don't really drill", rootCauseFlag: "open_play_only" },
      { id: "b", label: "We just warm up and rally a bit", rootCauseFlag: "random_drilling" },
      { id: "c", label: "I drill specific shots, but I pick them randomly", rootCauseFlag: "random_drilling" },
      { id: "d", label: "I drill specific weaknesses with a plan", rootCauseFlag: "well_coached" },
    ],
  },
  {
    id: "partner_access",
    prompt: "Do you have someone to drill with, and do you play people better than you?",
    type: "training",
    required: true,
    options: [
      { id: "a", label: "I have a reliable drilling partner and play up often", rootCauseFlag: "well_coached" },
      { id: "b", label: "Sometimes, but not consistently", rootCauseFlag: "unclear" },
      { id: "c", label: "Mostly stuck with my usual group, no real drilling partner", rootCauseFlag: "open_play_only" },
      { id: "d", label: "I almost only play open play with whoever's there", rootCauseFlag: "open_play_only" },
    ],
  },
  {
    id: "net_hold",
    prompt: "After the serve and return, how reliably do you and your partner get up to the kitchen line and hold it?",
    type: "skill",
    measures: "reset",
    required: true,
    options: [
      { id: "a", label: "Almost every point — we get up and stay there", skillLevel: 3 },
      { id: "b", label: "Most of the time, but we get pushed back a lot", skillLevel: 2 },
      { id: "c", label: "Inconsistent — we're often stuck mid-court or at the baseline", skillLevel: 1 },
      { id: "d", label: "We mostly play from the back, getting to the net is a struggle", skillLevel: 0 },
    ],
  },
  {
    id: "third_shot",
    prompt: "A deep return comes back and you go for a third-shot drop. Out of 10 in a real game, how many land in the kitchen without getting attacked?",
    type: "skill",
    measures: "third_shot_drop",
    required: true,
    options: [
      { id: "a", label: "7–10 — soft and unattackable most of the time", skillLevel: 3 },
      { id: "b", label: "4–6 — about half find the kitchen", skillLevel: 2 },
      { id: "c", label: "1–3 — most sit up or go into the net", skillLevel: 1 },
      { id: "d", label: "I usually just drive instead, the drop isn't reliable", skillLevel: 0 },
    ],
  },
  {
    id: "transition_reset",
    prompt: "You're caught in the transition zone (mid-court) and they drive a hard ball at your feet. What usually happens?",
    type: "skill",
    measures: "reset",
    required: true,
    options: [
      { id: "a", label: "I reset it softly into the kitchen and keep coming", skillLevel: 3 },
      { id: "b", label: "I get it back but it floats and sometimes gets attacked", skillLevel: 2 },
      { id: "c", label: "I pop it up and usually lose the point", skillLevel: 1 },
      { id: "d", label: "It handcuffs me — I can't really handle it", skillLevel: 0 },
    ],
  },
  {
    id: "net_defense",
    prompt: "You're at the kitchen line and someone speeds the ball up at your body or hip. What usually happens?",
    type: "skill",
    measures: "net_defense",
    required: true,
    options: [
      { id: "a", label: "I block or counter it back and stay in the point", skillLevel: 3 },
      { id: "b", label: "I get it back but it sits up for them", skillLevel: 2 },
      { id: "c", label: "I flinch or mishit — it's a coin flip", skillLevel: 1 },
      { id: "d", label: "I usually lose the point right there", skillLevel: 0 },
    ],
  },
  {
    id: "dink_patience",
    prompt: "In a long dinking rally at the kitchen, what usually ends it?",
    type: "skill",
    measures: "dink_patience",
    required: true,
    options: [
      { id: "a", label: "I stay patient and speed up only when they give me a ball that's actually attackable", skillLevel: 3 },
      { id: "b", label: "I just keep it going and wait for them to miss", skillLevel: 2 },
      { id: "c", label: "I get impatient and force a speed-up too early", skillLevel: 1 },
      { id: "d", label: "I make the first unforced error — net or out", skillLevel: 1 },
    ],
  },
  {
    id: "lose_reason",
    prompt: "In your own words: when you lose a game you feel like you should have won, what usually went wrong?",
    type: "text",
    required: true,
  },
];
